= image:icon_docker.svg["docker", width=64px] Docker cheat sheet
:author: Julien Morat
:email: julien.morat@gmail.com
:sectnums:
:toc: left
:toclevels: 1
:experimental:

== Cheat

=== build

Some examples

[source,bash]
----
#             PATH                                  Options       ==> IMAGE   repository    , tag
docker build  .                                    -t hello-world:1.0.1     # hello-world   , 1.0.1
docker build  git://github.com/naver/kapture                                # <none>        , <none>
docker build  git://github.com/naver/kapture#1.0.9 -t naver/kapture:1.0.9   # naver/kapture , 1.0.9
----

=== run

----
docker run hello-world
----

=== clean
[source,bash]
----
docker system prune    # stopped containers, dangling images, dangling build cache
docker system prune -a # unused images not just dangling ones
----


== Terminology

. `image` is a saved and archived machine state (like an .img of an SD card).
. `IMAGE ID` uniquely identified an image. It is 64 digit hex code truncated to 12 digits (e.g. 91c95931e552).
. `repository` is a collection of images. 'ubuntu' is a repository.
. `repository:tag` (I 'll call it `image alias`) is human-friendly alias to an `IMAGE ID`.
   The `tag` part usually refer to a version name, as such as 'hello-world:latest'
. `registry` is a server that stores and lets you distribute images.
. `container` is a running instance based (and possibly modified) on an image.
. `CONTAINER ID` uniquely identified a container.
. `NAME` is an alias to `CONTAINER ID`.

== format

You can customize the default formatting of `docker ps` command by setting the `.docker/config.json`

[source,bash]
mkdir ~/.docker && nano ~/.docker/config.json

For example:

..docker/config.json
[source,json]
----
{
  "psFormat": "table {{.Names}}\\t{{.Status}}\\t{{.RunningFor}}\\t{{.Image}}"
}
----

[cols="1,5", header=]
.format placeholders
|===
|Placeholder   |Description

|.ID           |Container ID
|.Image        |Image ID
|.Command      |Quoted command
|.CreatedAt    |Time when the container was created.
|.RunningFor   |Elapsed time since the container was started.
|.Ports        |Exposed ports.
|.State        |Container status (for example; “created”, “running”, “exited”).
|.Status       |Container status with details about duration and health-status.
|.Size         |Container disk size.
|.Names        |Container names.
|.Labels       |All labels assigned to the container.
|.Label        |Value of a specific label for this container. For example '{{.Label "com.docker.swarm.cpu"}}'
|.Mounts       |Names of the volumes mounted in this container.
|.Networks     |Names of the networks attached to this container.
|===

https://docs.docker.com/engine/reference/commandline/ps/#formatting[source]


== `CMD` VS `ENTRYPOINT`

- `CMD` is an instruction that is best to use if you need a default command which users can easily override.
- `ENTRYPOINT` is preferred when you want to define a container with a specific executable.

Prefer exec form (`["echo", "Hello World"]`) to prevent potential performance issues.

More : https://phoenixnap.com/kb/docker-cmd-vs-entrypoint[docker-cmd-vs-entrypoint]

== `PORT` VS `EXPOSE`

 - `port`: map the port from inside to outside the container.
 - `expose`: don't publish to the host machine - they’ll only be accessible to linked services.
               Only the internal port can be specified.

== Run as a non-root user

For Debian-based images, removing root from container can be done like this:


[source,bash]
----
RUN   groupadd -g 10001 dotnet \
&&    useradd -u 10000 -g dotnet dotnet \
&&    chown -R dotnet:dotnet /app

USER  dotnet:dotnet
----

NOTE: UIDs below 10000 are a security risk on several systems.

see more on https://github.com/dnaprawa/dockerfile-best-practices#alpine-is-not-always-the-best-choice[dockerfile-best-practices]