= image:synology_icon.svg["Synology", width=64px] Synology
:toc:

== ssh

=== enable service

To enable SSH access, go on DSM web interface :
- activate SSH in panel `config` > `terminal & SNMP`,
- change default port (one of most important point to secure your NAS),

connect through SSH as _root_ (the only user allowed on SSH):
- edit `/etc/passwd` (eg. `vi /etc/passwd`),
- for the user you want,  change the end of line `/sbin/nologin` with `/bin/ash`,
- save, quit and loggoff (`^D`).

to check :
- reconnect through SSH as user.

=== ssh key
As _user_, do:

Make sure you have home directory.

create ssh key :
[source,bash]
----
$> ssh-keygen -t dsa
----

Make sure home dir permission is `755` (cf: [superuser][su]) :
[source,bash]
----
$> cd
$> chmod 755 ~/
$> chmod 700 ~/.ssh
$> chmod 600 ~/.ssh/authorized_keys
----

Then, copy public key on remote server
[source,bash]
----
$> scp -P PORT .ssh/id_dsa.pub USER@REMOTE:.ssh/authorized_keys
----

WARNING: this will erase previously key set

replace:

  - PORT: by the port number you selected when you activated SSH (default is 23, but strongly recommend to change this),
  - USER: the user name on the remote server,
  - REMOTE : domain name (or ip) of the remote server.


https://superuser.com/questions/736055/ssh-with-no-password-passwordless-on-synology-dsm-5-as-other-non-root-user/769819#769819?newreg=593ce82fe74c491f80bb906c69644f49[SU]

=== Git server
Enable git server package in DSM, and allow port forwarding in ssh. Edit `/etc/ssh/ssh_config`

uncomment the following line :
----
AllowForwarding yes
----

== opkg packet manager

=== install
source: https://github.com/Entware/Entware-ng/wiki/Install-on-Synology-NAS

[source,bash]
----
$> sudo su
$> mkdir -p /volume1/@entware-ng/opt
# Remove /opt and create a symlink
$> rm -rf /opt
$> ln -sf /volume1/@entware-ng/opt /opt
# launch install script
$> wget -O - http://pkg.entware.net/binaries/armv7/installer/entware_install.sh | /bin/sh
# update
$> /opt/bin/opkg update
$> /opt/bin/opkg upgrade
$> /opt/bin/opkg install nano
----


To add `/opt` to `$PATH` : add the following line in the end of `/root/.profile` and `/etc/profile` file

./root/.profile
[source,bash]
----
. /opt/etc/profile
----

NOTE: As of DSM 6.0, `/etc/rc.local` is no longer executed as part of the boot process.

=== ipkg packet manager (deprecated)
Source: http://blog.nouveauxterritoires.fr/fr/2014/04/23/installer-la-commande-ipkg-sur-un-nas-synology-recent/[installer-la-commande-ipkg-sur-un-nas-synology-recent]

refer to old version : https://github.com/jujumo/memento/commit/1058728796f83f32c82ca5bba62b9afbee307d3d#diff-0d4f386fcd35e6f4a6911720a6be9021da984fc70767fb9229482c1d993e032b

== crontab
NOTE: `/etc/crontab` is reset at each synology updates. I recommend to use the synology cron handler (in DSM) instead of directly edit crontab by your own.

== rsync

To clone a directory
[source,bash]
----
$> rsync `# do not use -a avoid perms/owner preservation` \
        --rsh 'ssh -p 22' `# Specify ssh options to use` \
        --rsync-path=PATH `# Specify path of rsync on remote` \
        --verbose --progress \
        --recursive \
        --compress        `# Compress file data during the transfer` \
        --partial         `# Keep partially transferred files` \
        --partial-dir=DIR `# put a partially transferred file into DIR` \
        --links           `# Copy symlinks as symlinks` \
        --times           `# preserve modification times (important for update)` \
        --update          `# Skip files that are newer on the receiver` \
        --checksum        `# replace the times+sizes heuristic with sizes+md5 one` \
        --delete          `# Delete extraneous files from destination dirs` \
        --exclude '@eaDir' `# exclude syno junk metadata` \
        /sourceDir/ IP:/destDir/
----

Making versioned archive
[source,bash]
----
...
        --backup   `# make a backup of what changed on destination` \
        --backup-dir=/destDir/$( date +"%Y-%m-%d-%H-%M" )/  `#` \
...
----

see more link:rsync.adoc[rsync.adoc]

https://www.rsyncinator.app/web