= image:icon_linux.svg["X", width=64px] Linux cheat code
:toc:

## Do for all files

[source,bash]
----
find . -name \*.txt -type f -print0 | xargs -0 -n1 echo
----

### Search within files

-- source : https://www.everythingcli.org/find-exec-vs-find-xargs/

[source,bash]
----
find . -name \*.txt -type f -print0 | xargs -0 grep -Hn '$USER'
----

 - `find .` find all files, folders, symlinks, etc in the current directory recursively
 - `-name \*.txt` Its filename must end with .txt
 - `-type f` Only search for files (not folders)
 - `-print0` and `-0` use ASCII NULL character.
 - `-H` Always print filename headers with output lines.
 - `-n` Each output line is preceded by its relative line number in the file, starting at line 1.


## usefull commands

### grep
search into files of current working dir:

[source,bash]
grep -r PATTERN

 - `-r` :

### xargs

 - `-p` : *print* & *prompt* the user to run it
 - `-I %` : This replaces occurrences of the argument with the argument passed to xargs (`%` in that case).

.example
[source,bash]
cat /etc/passwd | xargs -I % echo "### % ###"

### diff

[source,bash]
diff <(ls new_dir) <(old_dir)

### awk

TODO

### sed

TODO

### watch

execute a command or program periodically

[source,bash]
watch -d ifconfig

- `-d` highlights the changes in the command output.


### expect
command talks to other interactive programs

.script.sh
[source,expect]
----
#!/usr/bin/expect -f
spawn ssh debian@192.168.7.2
expect "debian@192.168.7.2's password:"
send "temppwd\r"
set prompt_re {\$ $}
expect -re $prompt_re
send "mkdir -p emma && cd emma\r"
expect -re $prompt_re
interact
----