# image:icon_ffmpeg.svg["FFMPEG", width=64px] FFMPEG
:toc: macro

Official: https://www.ffmpeg.org/[www.ffmpeg.org]

## Basic
```
ffmpeg -i <input_file> <output_file>
```

toc::[]

## Presets
`ultrafast`, `superfast`, `veryfast`, `faster`, `fast`, `medium`, `slow`, `slower`, `veryslow`

.example
```
ffmpeg -i video.mov -preset veryslow video.mp4
```

## video <==> images

### video => images

.example
```bash
ffmpeg -i video.mov -q:v 1 %05d.jpg
```

[cols=">1m,<8", frame=topbot, grid=none]
|=====================================
|`-q:v 1` | Set the __quality__ of the video encoder, where the -q means quality and the :v means video.
Values range from 1 to 31, where lower means better.
|=====================================

.example
```bash
ffmpeg -i video.mov -q:v 1 -vframes 1 -ss 00:10:00 image.jpg
```
extracts a single image at frame 10:

### video <= images

.example
```bash
ffmpeg -framerate 1/5 -i img%03d.png -c:v libx264 -r 30 -pix_fmt yuv420p out.mp4
```

NOTE: Use `-loop 1` as an input option for an infinite loop, and then use `-t 00:30:00` as an output option to cut off the video at thirty minutes.

## Timing


### trim
You can use the -ss option to specify a start timestamp, and the -t option to specify the encoding duration. The timestamps need to be in HH:MM:SS.xxx format or in seconds.


.example
```bash
ffmpeg -i input.wmv -ss 00:00:30.0 -c copy -t 00:00:10.0 output.wmv
ffmpeg -i input.wmv -ss 30 -c copy -t 10 output.wmv
```

### framerate

.example
```bash
ffmpeg -i input.wmv -framerate 1 output.wmv
```

### Patrol Cycle (back and forth)

.example
```bash
ffmpeg -i input.mp4 -filter_complex "[0]reverse[r];[0][r]concat,setpts=N/25/TB" output.mp4
```
The ```setpts``` is applied to avoid frame drops, and the value ```25``` should be replaced with the framerate of the clip.

## Geometry

### crop
```
-filter:v "crop=100:100:12:34"
```

```
-filter:v "crop=200:ih:12:34"
```

### scale

```
-filter:v scale=iw*2:-1"
```

### rotation

```
-filter:v "transpose=1"
```
with possible values :
- 0 = 90CounterCLockwise and Vertical Flip (default)
- 1 = 90Clockwise
- 2 = 90CounterClockwise
- 3 = 90Clockwise and Vertical Flip

## Stabilization
* https://ffmpeg.org/ffmpeg-filters.html#vidstabdetect
* https://ffmpeg.org/ffmpeg-filters.html#vidstabtransform-1

.example of first pass
```sh
ffmpeg -i movie.mp4 -vf vidstabdetect=stepsize=6:shakiness=10:accuracy=15:result=motions.trf -f null -
```

.example of second pass
```sh
ffmpeg -i movie.mp4 -vf vidstabtransform=input=motions.trf:smoothing=60:relative=1,unsharp=5:5:0.8:3:3:0.4 -vcodec libx264 -preset veryslow -tune film -acodec copy -y smooth.mp4
```

## stereo 3D
https://trac.ffmpeg.org/wiki/Stereoscopic[source]

NOTE: to use filter `stereo3d`, you may have a recent version of ffmpeg.

side by side half width left first to Red cyan gray/monochrome

.example
```bash
ffmpeg -i SbS.mp4 -vf stereo3d=sbs2l:arbg -y anaglyph.mp4
```
with :
[cols=">1m,<8", frame=topbot, grid=none]
|=====================================
| sbs | side by side
| 2   | half width
| l   | left first
| a   | anaglyph
| rbg | red blue grey
|=====================================

If the output video is still squeezed, use :

.example
```bash
ffmpeg -i SbS.mp4 -vf "stereo3d=sbsl:arcg,scale=iw*2:ih" -y anaglyph.mp4
```
with :
[cols=">1m,<8", frame=topbot, grid=none]
|=====================================
| sbsl          | side by side left first
| arcg          | anaglyph red/cyan gray
| scale=iw*2:ih | squeeze horizontally
|=====================================

## Audio
.example
```bash
ffmpeg -i input.wav -codec:a libmp3lame -qscale:a 0 output.mp3
```
0 is better
